# This docker-compose.yml is for development purposes during development of the installer or creating a local AIP build during testing
# Actual Github workflows directly uses FEMR/femr docker-compose.yml along with ./docker-compose.override.yml
# KEEP THIS COMMENT!!!

# copied from FEMR/femr/docker-compose.yml on 5/13/2025 wth adjustment to femr service image origin
# or copy paste in latest .yml from FEMR/femr and update comment date
version: "3"
services:

  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'femr_db'
      MYSQL_USER: 'femr'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command:
      - "mysqld"
      - "--log-bin-trust-function-creators=1"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  femr:
    build: .
    depends_on: 
      db:
        condition: service_healthy
    tty: true
    restart: on-failure:10
    ports:
      - '9000:9000'

    environment:
      DB_URL: 'jdbc:mysql://db:3306/femr_db?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true'
      DB_USER: 'femr'
      DB_PASS: 'password'
      IS_DOCKER: 'true'

    volumes:
      - ./speedtest:/usr/src/speedtest


# volume need to be manually created; femr.ps1 includes creation
volumes:
  db-data:
    external: true  
    name: femr-ext-volume